version: "3"

services:
  apartment-service:
    container_name: apartment-service
    image: every-apart-apartment-service:0.0.1
    ports:
      - "8080:8080"
    environment:
      EVERYAPART_GOOPENAPI_ACCESSKEY: "{accessKey}"
      SPRING_DATASOURCE_URL : "jdbc:postgresql://apartment-db:5432/everyapart"
      SPRING_DATASOURCE_USERNAME : "postgres"
      SPRING_DATASOURCE_PASSWORD : "postgres"
      SPRING_DATASOURCE_DRIVERCLASSNAME: "org.postgresql.Driver"
  region-service:
    container_name: region-service
    image: every-apart-region-service:0.0.1
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://region-db:5432/everyapart"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "postgres"
      SPRING_DATASOURCE_DRIVERCLASSNAME: "org.postgresql.Driver"
  apartment-db:
    image: postgres:latest
    container_name: apartment-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "everyapart"
      SPRING_PROFILES_ACTIVE: "dev"
    volumes:
      - apartment-db-volume:/var/lib/postgresql/data
  region-db:
    image: postgres:latest
    container_name: region-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "everyapart"
    volumes:
      - region-db-volume:/var/lib/postgresql/data
volumes:
  apartment-db-volume:
    external: true
  region-db-volume:
    external: true
